use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::error::{Error, Result};

/// Live-dashboard settings. The "$ saved" baseline: cloud $/million-tokens the
/// local run is priced against. Default 0.0 → the dashboard shows "—" (unset).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct DashboardConfig {
    /// USD per million **input** tokens for the cloud baseline (used when
    /// `saved_model` is not set or not recognised).
    pub saved_input_per_mtok: f64,
    /// USD per million **output** tokens for the cloud baseline (used when
    /// `saved_model` is not set or not recognised).
    pub saved_output_per_mtok: f64,
    /// Optional Claude model name; when set and recognised, auto-fills
    /// `saved_input_per_mtok` / `saved_output_per_mtok` with current pricing.
    /// Recognised values: `claude-fable-5`, `claude-mythos-5`,
    /// `claude-opus-4-8`/`4-7`/`4-6`, `claude-sonnet-4-6`, `claude-haiku-4-5`.
    pub saved_model: Option<String>,
}

impl Default for DashboardConfig {
    fn default() -> Self {
        Self {
            saved_input_per_mtok: 0.0,
            saved_output_per_mtok: 0.0,
            saved_model: None,
        }
    }
}

/// Context-optimization settings (M10). `output_filter` is the kill-switch for
/// boundary output filtering — default on; set false to restore raw head+tail
/// truncation with no recovery file.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(default)]
pub struct ContextConfig {
    pub output_filter: bool,
}

impl Default for ContextConfig {
    fn default() -> Self {
        Self {
            output_filter: true,
        }
    }
}

/// Governor hard-fail thresholds. Tune these to match your model's cadence.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(default)]
pub struct GovernorConfig {
    /// Consecutive identical tool calls before `IdenticalToolCallRepetition`
    /// hard-fail. Default 6.
    pub identical_call_threshold: usize,
    /// Consecutive turns with author-attributed verifier errors before
    /// `VerifierFailurePersistent` hard-fail. Default 6.
    pub verifier_persistence_threshold: usize,
    /// Single tool-output bytes before `RunawayOutput` hard-fail.
    /// Default 102400 (100 KB).
    pub runaway_output_bytes: usize,
}

impl Default for GovernorConfig {
    fn default() -> Self {
        Self {
            identical_call_threshold: 6,
            verifier_persistence_threshold: 6,
            runaway_output_bytes: 100 * 1024,
        }
    }
}

/// Per-model knob overrides. Each `Some` field replaces the corresponding global
/// `[executor]`/`[governor]` default when this model is the active executor
/// model; each `None` field inherits the global value. Keyed by exact model id
/// in the `[models]` table (e.g. `[models."Qwen/Qwen3.6-27B-FP8"]`).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct ModelOverride {
    pub task_tracking: Option<bool>,
    pub temperature: Option<f64>,
    pub seed: Option<u64>,
    pub identical_call_threshold: Option<usize>,
    pub verifier_persistence_threshold: Option<usize>,
    pub runaway_output_bytes: Option<usize>,
}

/// Per-project identity. The `id` UUID is generated by `rexymcp init` and
/// stored in the project's `rexymcp.toml`. Used to scope telemetry records to
/// the project regardless of filesystem path.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct ProjectConfig {
    pub id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct Config {
    pub project: ProjectConfig,
    pub executor: ExecutorConfig,
    pub commands: CommandConfig,
    pub budget: BudgetConfig,
    pub telemetry: TelemetryConfig,
    pub dashboard: DashboardConfig,
    pub context: ContextConfig,
    pub governor: GovernorConfig,
    pub models: HashMap<String, ModelOverride>,
}

/// Cross-project telemetry store. `None` disables telemetry emission.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TelemetryConfig {
    pub dir: Option<PathBuf>,
}

/// The local LLM the executor drives.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutorConfig {
    /// "openai" | "ollama" | "lmstudio" — all OpenAI-compatible.
    pub provider: String,
    /// Model identifier as the endpoint knows it (e.g. "qwen2.5-coder").
    pub model: String,
    /// OpenAI-compatible base URL, e.g. "http://localhost:1234/v1".
    pub base_url: String,
    /// Optional API key; local endpoints usually ignore it.
    pub api_key: Option<String>,
    /// Budget (seconds) for the wait before the first token of a completion (prefill).
    #[serde(default = "default_first_token_timeout_secs")]
    pub first_token_timeout_secs: u64,
    /// Budget (seconds) for the gap between tokens once streaming has begun.
    #[serde(default = "default_stream_idle_timeout_secs")]
    pub stream_idle_timeout_secs: u64,
    /// Sampling temperature sent on every chat request. `None` omits the key,
    /// letting the endpoint apply its own default.
    #[serde(default)]
    pub temperature: Option<f64>,
    /// Deterministic sampling seed sent on every chat request. `None` omits it.
    #[serde(default)]
    pub seed: Option<u64>,
    /// Whether the loop seeds a per-session task list from the phase doc's
    /// `## Spec` and emits `TaskUpdate` events as the executor flips state
    /// (M12 Arc A). Default on; set false for a control run with no task
    /// tracking (the seeding emit is byte-for-byte suppressed).
    #[serde(default = "default_task_tracking")]
    pub task_tracking: bool,
}

fn default_first_token_timeout_secs() -> u64 {
    600
}

fn default_stream_idle_timeout_secs() -> u64 {
    240
}

fn default_task_tracking() -> bool {
    true
}

impl Default for ExecutorConfig {
    fn default() -> Self {
        Self {
            provider: "openai".into(),
            model: String::new(),
            base_url: "http://localhost:1234/v1".into(),
            api_key: None,
            first_token_timeout_secs: default_first_token_timeout_secs(),
            stream_idle_timeout_secs: default_stream_idle_timeout_secs(),
            temperature: None,
            seed: None,
            task_tracking: default_task_tracking(),
        }
    }
}

/// Resolves the {FORMAT,BUILD,LINT,TEST}_COMMAND placeholders for the
/// target project the executor works in.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CommandConfig {
    pub format: Option<String>,
    pub build: Option<String>,
    pub lint: Option<String>,
    pub test: Option<String>,
    pub lint_fix: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BudgetConfig {
    /// Model's context-window size in tokens.
    pub context_length: usize,
    /// % of the model's context window the loop may fill before compacting.
    pub max_context_pct: u8,
    /// Hard cap on executor turns in one phase before budget_exceeded.
    pub max_turns: u32,
    /// Escalation slots (briefings returned to the architect) per phase.
    pub escalation_slots: u32,
}

impl Default for BudgetConfig {
    fn default() -> Self {
        Self {
            context_length: 32768,
            max_context_pct: 70,
            max_turns: 200,
            escalation_slots: 1,
        }
    }
}

fn expand_tilde(path: PathBuf) -> PathBuf {
    let s = path.to_string_lossy();
    if let Some(rest) = s.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return PathBuf::from(home).join(rest);
        }
    } else if s == "~"
        && let Ok(home) = std::env::var("HOME")
    {
        return PathBuf::from(home);
    }
    path
}

impl Config {
    pub fn load(path: &Path) -> Result<Self> {
        let mut config = Config::default();

        if path.exists() {
            let content = std::fs::read_to_string(path)?;
            let loaded: Config =
                toml::from_str(&content).map_err(|e| Error::Config(e.to_string()))?;
            config = loaded;
        }

        config.telemetry.dir = config.telemetry.dir.map(expand_tilde);

        Ok(config)
    }

    pub fn apply_overrides(&mut self, get: impl Fn(&str) -> Option<String>) {
        if let Some(v) = get("REXYMCP_PROVIDER") {
            self.executor.provider = v;
        }
        if let Some(v) = get("REXYMCP_MODEL") {
            self.executor.model = v;
        }
        if let Some(v) = get("REXYMCP_BASE_URL") {
            self.executor.base_url = v;
        }
        if let Some(v) = get("REXYMCP_API_KEY") {
            self.executor.api_key = Some(v);
        }
    }

    pub fn apply_env(&mut self) -> Result<()> {
        self.apply_overrides(|k| std::env::var(k).ok());
        Ok(())
    }

    pub fn load_with_env(path: &Path) -> Result<Self> {
        let mut config = Self::load(path)?;
        config.apply_env()?;
        Ok(config)
    }

    /// Apply the per-model override for `model` (exact-match lookup in
    /// `[models]`) on top of the global `[executor]`/`[governor]` defaults,
    /// mutating `self` so downstream reads see resolved values. A model with no
    /// `[models]` entry leaves every global untouched.
    pub fn resolve_for_model(&mut self, model: &str) {
        let Some(over) = self.models.get(model).cloned() else {
            return;
        };
        if let Some(v) = over.task_tracking {
            self.executor.task_tracking = v;
        }
        if let Some(v) = over.temperature {
            self.executor.temperature = Some(v);
        }
        if let Some(v) = over.seed {
            self.executor.seed = Some(v);
        }
        if let Some(v) = over.identical_call_threshold {
            self.governor.identical_call_threshold = v;
        }
        if let Some(v) = over.verifier_persistence_threshold {
            self.governor.verifier_persistence_threshold = v;
        }
        if let Some(v) = over.runaway_output_bytes {
            self.governor.runaway_output_bytes = v;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn default_config_targets_local_lmstudio() {
        let cfg = Config::default();
        assert_eq!(cfg.executor.provider, "openai");
        assert_eq!(cfg.executor.base_url, "http://localhost:1234/v1");
        assert_eq!(cfg.budget.max_context_pct, 70);
    }

    #[test]
    fn load_missing_file_returns_default() {
        let cfg = Config::load(Path::new("/nonexistent/path.toml")).unwrap();
        let defaults = Config::default();
        assert_eq!(cfg.executor.provider, defaults.executor.provider);
        assert_eq!(cfg.executor.model, defaults.executor.model);
        assert_eq!(cfg.executor.base_url, defaults.executor.base_url);
        assert_eq!(cfg.budget.max_context_pct, defaults.budget.max_context_pct);
    }

    #[test]
    fn load_parses_toml_executor_block() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(
            f,
            r#"[executor]
provider = "ollama"
model = "qwen2.5-coder"
base_url = "http://localhost:11434/v1"

[commands]

[budget]
context_length = 128000
max_context_pct = 80
max_turns = 50
escalation_slots = 2
"#
        )
        .unwrap();
        drop(f);

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.provider, "ollama");
        assert_eq!(cfg.executor.model, "qwen2.5-coder");
        assert_eq!(cfg.executor.base_url, "http://localhost:11434/v1");
        assert_eq!(cfg.budget.context_length, 128000);
        assert_eq!(cfg.budget.max_context_pct, 80);
        assert_eq!(cfg.budget.max_turns, 50);
        assert_eq!(cfg.budget.escalation_slots, 2);
    }

    #[test]
    fn load_malformed_toml_is_config_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.toml");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(f, "this is not valid toml {{{{").unwrap();
        drop(f);

        let result = Config::load(&path);
        assert!(result.is_err());
        match result.unwrap_err() {
            Error::Config(_) => {}
            other => panic!("expected Error::Config, got {other:?}"),
        }
    }

    #[test]
    fn env_override_beats_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(
            f,
            r#"[executor]
provider = "openai"
model = "model-a"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#
        )
        .unwrap();
        drop(f);

        let mut cfg = Config::load(&path).unwrap();
        cfg.apply_overrides(|k| {
            if k == "REXYMCP_MODEL" {
                Some("model-b".into())
            } else {
                None
            }
        });

        assert_eq!(cfg.executor.model, "model-b");
    }

    #[test]
    fn telemetry_default_is_none() {
        let cfg = Config::default();
        assert_eq!(cfg.telemetry.dir, None);
    }

    #[test]
    fn telemetry_absent_section_is_none() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.telemetry.dir, None);
    }

    #[test]
    fn telemetry_explicit_dir_is_some() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[telemetry]
dir = "/var/lib/rexymcp"
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.telemetry.dir, Some(PathBuf::from("/var/lib/rexymcp")));
    }

    #[test]
    fn telemetry_tilde_dir_expands_to_home() {
        let home = std::env::var("HOME").expect("HOME must be set");
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[telemetry]
dir = "~/.rexymcp/telemetry"
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        let expected = PathBuf::from(&home).join(".rexymcp/telemetry");
        assert_eq!(cfg.telemetry.dir, Some(expected));
    }

    #[test]
    fn config_defaults_first_token_and_idle_timeouts() {
        let cfg = ExecutorConfig::default();
        assert_eq!(cfg.first_token_timeout_secs, 600);
        assert_eq!(cfg.stream_idle_timeout_secs, 240);
    }

    #[test]
    fn config_loads_overridden_timeouts() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
first_token_timeout_secs = 300
stream_idle_timeout_secs = 45

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.first_token_timeout_secs, 300);
        assert_eq!(cfg.executor.stream_idle_timeout_secs, 45);
    }

    #[test]
    fn config_omits_timeouts_keeps_defaults() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.first_token_timeout_secs, 600);
        assert_eq!(cfg.executor.stream_idle_timeout_secs, 240);
    }

    #[test]
    fn config_defaults_sampling_settings_to_none() {
        let cfg = ExecutorConfig::default();
        assert_eq!(cfg.temperature, None);
        assert_eq!(cfg.seed, None);
    }

    #[test]
    fn config_loads_sampling_settings() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
temperature = 0.2
seed = 42

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.temperature, Some(0.2));
        assert_eq!(cfg.executor.seed, Some(42));
    }

    #[test]
    fn config_omits_sampling_settings_keeps_none() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.temperature, None);
        assert_eq!(cfg.executor.seed, None);
    }

    #[test]
    fn dashboard_config_defaults_to_zero() {
        let cfg = Config::default();
        assert_eq!(cfg.dashboard.saved_input_per_mtok, 0.0);
        assert_eq!(cfg.dashboard.saved_output_per_mtok, 0.0);
    }

    #[test]
    fn config_loads_dashboard_rates() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[dashboard]
saved_input_per_mtok = 3.0
saved_output_per_mtok = 15.0
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.dashboard.saved_input_per_mtok, 3.0);
        assert_eq!(cfg.dashboard.saved_output_per_mtok, 15.0);
    }

    #[test]
    fn lint_fix_field_defaults_to_none_when_absent() {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        std::fs::write(
            &path,
            r#"
[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]
format = "cargo fmt"
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert_eq!(
            cfg.commands.lint_fix, None,
            "lint_fix must default to None when absent from [commands]"
        );
        assert_eq!(cfg.commands.format.as_deref(), Some("cargo fmt"));
    }

    #[test]
    fn context_config_defaults_output_filter_on() {
        let cfg = ContextConfig::default();
        assert!(cfg.output_filter, "output_filter should default to true");

        // A Config parsed from TOML with no [context] section should also default to true
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert!(
            cfg.context.output_filter,
            "context.output_filter should default to true when [context] section is absent"
        );
    }

    #[test]
    fn context_output_filter_can_be_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[context]
output_filter = false
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert!(
            !cfg.context.output_filter,
            "output_filter should be false when explicitly set"
        );
    }

    #[test]
    fn governor_config_round_trips_from_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[governor]
identical_call_threshold = 10
verifier_persistence_threshold = 8
runaway_output_bytes = 204800
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.governor.identical_call_threshold, 10);
        assert_eq!(cfg.governor.verifier_persistence_threshold, 8);
        assert_eq!(cfg.governor.runaway_output_bytes, 204800);
    }

    #[test]
    fn executor_task_tracking_defaults_on() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert!(
            cfg.executor.task_tracking,
            "executor.task_tracking should default to true when absent"
        );
    }

    #[test]
    fn executor_task_tracking_can_be_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
task_tracking = false

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();
        let cfg = Config::load(&path).unwrap();
        assert!(
            !cfg.executor.task_tracking,
            "executor.task_tracking should be false when explicitly set"
        );
    }

    #[test]
    fn model_override_section_parses_from_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[models."Qwen/Qwen3.6-27B-FP8"]
temperature = 0.2
task_tracking = false
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert!(
            cfg.models.contains_key("Qwen/Qwen3.6-27B-FP8"),
            "models map must contain the key from the TOML section"
        );
        let over = cfg.models.get("Qwen/Qwen3.6-27B-FP8").unwrap();
        assert_eq!(over.temperature, Some(0.2));
        assert_eq!(over.task_tracking, Some(false));
    }

    #[test]
    fn models_section_absent_is_empty_map() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1
"#,
        )
        .unwrap();

        let cfg = Config::load(&path).unwrap();
        assert!(
            cfg.models.is_empty(),
            "models map must be empty when no [models] section is present"
        );
    }

    #[test]
    fn resolve_for_model_applies_matching_override() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
task_tracking = true
temperature = 0.8
seed = 1

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[governor]
identical_call_threshold = 6
verifier_persistence_threshold = 6
runaway_output_bytes = 102400

[models."Qwen/Qwen3.6-27B-FP8"]
task_tracking = false
temperature = 0.2
seed = 7
identical_call_threshold = 8
"#,
        )
        .unwrap();

        let mut cfg = Config::load(&path).unwrap();
        cfg.resolve_for_model("Qwen/Qwen3.6-27B-FP8");

        assert!(!cfg.executor.task_tracking);
        assert_eq!(cfg.executor.temperature, Some(0.2));
        assert_eq!(cfg.executor.seed, Some(7));
        assert_eq!(cfg.governor.identical_call_threshold, 8);
    }

    #[test]
    fn resolve_for_model_leaves_unset_fields_global() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
task_tracking = true
seed = 99

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[governor]
identical_call_threshold = 6
verifier_persistence_threshold = 6
runaway_output_bytes = 102400

[models."test-model"]
temperature = 0.1
"#,
        )
        .unwrap();

        let mut cfg = Config::load(&path).unwrap();
        cfg.resolve_for_model("test-model");

        // temperature was overridden
        assert_eq!(cfg.executor.temperature, Some(0.1));
        // all others remain at their global values
        assert!(cfg.executor.task_tracking);
        assert_eq!(cfg.executor.seed, Some(99));
        assert_eq!(cfg.governor.identical_call_threshold, 6);
        assert_eq!(cfg.governor.verifier_persistence_threshold, 6);
        assert_eq!(cfg.governor.runaway_output_bytes, 102400);
    }

    #[test]
    fn resolve_for_model_unknown_model_is_noop() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
task_tracking = true
temperature = 0.5

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[governor]
identical_call_threshold = 6
verifier_persistence_threshold = 6
runaway_output_bytes = 102400

[models."some-other-model"]
task_tracking = false
temperature = 0.1
"#,
        )
        .unwrap();

        let mut cfg = Config::load(&path).unwrap();
        cfg.resolve_for_model("unknown-model");

        assert!(cfg.executor.task_tracking);
        assert_eq!(cfg.executor.temperature, Some(0.5));
        assert_eq!(cfg.governor.identical_call_threshold, 6);
        assert_eq!(cfg.governor.verifier_persistence_threshold, 6);
        assert_eq!(cfg.governor.runaway_output_bytes, 102400);
    }

    #[test]
    fn resolve_for_model_is_exact_match() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(
            &path,
            r#"[executor]
provider = "openai"
model = "m"
base_url = "http://localhost:1234/v1"
task_tracking = true

[commands]

[budget]
context_length = 32768
max_context_pct = 70
max_turns = 40
escalation_slots = 1

[models."qwen"]
task_tracking = false
"#,
        )
        .unwrap();

        let mut cfg = Config::load(&path).unwrap();
        cfg.resolve_for_model("qwen2.5-coder");

        assert!(
            cfg.executor.task_tracking,
            "prefix 'qwen' must not match model 'qwen2.5-coder'"
        );
    }
}
