use std::fs;
use std::io::Write;
use std::path::Path;

const TEMPLATE: &str = r#"# rexymcp.toml — executor configuration for this project.
# Generated by `rexymcp init`. Adjust values to match your setup.
# Reference: https://github.com/anthropics/rexyMCP

[executor]
provider = "openai"               # openai | ollama | lmstudio (all OpenAI-compatible)
model = "qwen2.5-coder-32b"       # model id as the endpoint knows it
base_url = "http://localhost:1234/v1"
# api_key = ""                    # optional; most local endpoints ignore it
# temperature = 0.2               # sampling temperature (omit for endpoint default)
# first_token_timeout_secs = 600  # wait before first token in seconds (default 600)
# stream_idle_timeout_secs = 240  # gap between tokens before timeout (default 240)
# task_tracking = true            # seed + track a per-session task list from the phase Spec (M12)

[budget]
context_length = 32768            # model context window in tokens
max_context_pct = 70              # trigger compaction above this % (0–100)
max_turns = 200                   # hard cap on executor turns per phase
escalation_slots = 1              # turns reserved for the final command set retry

[governor]
identical_call_threshold = 6      # consecutive identical tool calls → hard-fail
verifier_persistence_threshold = 6 # consecutive turns with verifier errors → hard-fail
runaway_output_bytes = 102400     # single tool output bytes → hard-fail (100 KB)

[commands]
# format = "cargo fmt --all"
# build = "cargo build"
# lint = "cargo clippy --all-targets --all-features -- -D warnings"
# test = "cargo test"
# lint_fix = "cargo clippy --fix --allow-dirty"

[context]
output_filter = true              # filter/truncate bash output to conserve context

[dashboard]
# saved_input_per_mtok = 3.0      # $/Mtok input tokens saved vs cloud baseline
# saved_output_per_mtok = 15.0    # $/Mtok output tokens saved vs cloud baseline

[telemetry]
# dir = "/path/to/shared/telemetry"  # cross-project PhaseRun telemetry store
"#;

pub fn run(dir: &Path, force: bool) -> anyhow::Result<()> {
    if !dir.is_dir() {
        return Err(anyhow::anyhow!("not a directory: {}", dir.display()));
    }

    let path = dir.join("rexymcp.toml");

    if path.exists() && !force {
        eprintln!("rexymcp.toml already exists — use --force to overwrite");
        return Err(anyhow::anyhow!("rexymcp.toml already exists"));
    }

    let mut file = fs::File::create(&path)?;
    file.write_all(TEMPLATE.as_bytes())?;

    println!("wrote rexymcp.toml");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rexymcp_executor::config::Config;
    use tempfile::TempDir;

    #[test]
    fn init_writes_toml() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(dir.path().join("rexymcp.toml").exists());
    }

    #[test]
    fn init_writes_parseable_config() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        let path = dir.path().join("rexymcp.toml");
        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.provider, "openai");
        assert_eq!(cfg.executor.model, "qwen2.5-coder-32b");
        assert_eq!(cfg.executor.base_url, "http://localhost:1234/v1");
        assert_eq!(cfg.budget.context_length, 32768);
        assert_eq!(cfg.budget.max_context_pct, 70);
        assert_eq!(cfg.budget.max_turns, 200);
        assert_eq!(cfg.budget.escalation_slots, 1);
        assert_eq!(cfg.governor.identical_call_threshold, 6);
        assert_eq!(cfg.governor.verifier_persistence_threshold, 6);
        assert_eq!(cfg.governor.runaway_output_bytes, 102400);
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        let result = run(dir.path(), false);
        assert!(result.is_err());

        // File must still contain "OLD"
        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, "OLD");
    }

    #[test]
    fn init_force_overwrites() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        run(dir.path(), true).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert_ne!(content, "OLD");
        assert!(content.starts_with("# rexymcp.toml"));
    }

    #[test]
    fn init_does_not_write_mcp_json() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(!dir.path().join(".mcp.json").exists());
    }
}
