use std::fs;
use std::io::Write;
use std::path::Path;

use uuid::Uuid;

fn generate_config(project_id: &str) -> String {
    format!(
        r#"# rexymcp.toml — executor configuration for this project.
# Generated by `rexymcp init`. Adjust values to match your setup.
# Reference: https://github.com/anthropics/rexyMCP

[project]
id = "{project_id}"              # stable UUID — identifies this project in telemetry

[executor]
provider = "openai"               # openai | ollama | lmstudio (all OpenAI-compatible)
model = "qwen2.5-coder-32b"       # model id as the endpoint knows it
base_url = "http://localhost:1234/v1"
# api_key = ""                    # optional; most local endpoints ignore it
# temperature = 0.2               # sampling temperature (omit for endpoint default)
# first_token_timeout_secs = 600  # wait before first token in seconds (default 600)
# stream_idle_timeout_secs = 240  # gap between tokens before timeout (default 240)
# task_tracking = true            # seed + track a per-session task list from the phase Spec (M12)

[budget]
context_length = 32768            # model context window in tokens
max_context_pct = 70              # trigger compaction above this % (0–100)
max_turns = 200                   # hard cap on executor turns per phase
escalation_slots = 1              # turns reserved for the final command set retry

[governor]
identical_call_threshold = 6      # consecutive identical tool calls → hard-fail
verifier_persistence_threshold = 6 # consecutive turns with verifier errors → hard-fail
runaway_output_bytes = 102400     # single tool output bytes → hard-fail (100 KB)

# [models."<model-id>"]              # per-model knob overrides; key is the exact
#                                    # active model id (no prefix/substring match).
#                                    # Any key omitted here inherits the global value above.
# task_tracking = false              # override [executor] task_tracking for this model
# temperature = 0.2                  # override [executor] temperature
# seed = 7                           # override [executor] seed
# identical_call_threshold = 8       # override [governor] identical_call_threshold
# verifier_persistence_threshold = 8 # override [governor] verifier_persistence_threshold
# runaway_output_bytes = 204800      # override [governor] runaway_output_bytes

[commands]
# format = "cargo fmt --all"
# build = "cargo build"
# lint = "cargo clippy --all-targets --all-features -- -D warnings"
# test = "cargo test"
# lint_fix = "cargo clippy --fix --allow-dirty"

[context]
output_filter = true              # filter/truncate bash output to conserve context

[dashboard]
# saved_model = "claude-opus-4-8"   # auto-fill rates for a known Claude model
#   known models: claude-fable-5 ($10/$50/MTok), claude-opus-4-8 ($5/$25/MTok),
#   claude-sonnet-4-6 ($3/$15/MTok), claude-haiku-4-5 ($1/$5/MTok)
# Or set rates directly (saved_model overrides these when both are set):
# saved_input_per_mtok = 5.0        # $/MTok input tokens saved vs cloud baseline
# saved_output_per_mtok = 25.0      # $/MTok output tokens saved vs cloud baseline

[telemetry]
# dir = "/path/to/shared/telemetry"  # cross-project PhaseRun telemetry store
"#
    )
}

pub fn run(dir: &Path, force: bool) -> anyhow::Result<()> {
    if !dir.is_dir() {
        return Err(anyhow::anyhow!("not a directory: {}", dir.display()));
    }

    let path = dir.join("rexymcp.toml");

    if path.exists() && !force {
        eprintln!("rexymcp.toml already exists — use --force to overwrite");
        return Err(anyhow::anyhow!("rexymcp.toml already exists"));
    }

    let project_id = Uuid::new_v4().to_string();
    let config = generate_config(&project_id);

    let mut file = fs::File::create(&path)?;
    file.write_all(config.as_bytes())?;

    println!("wrote rexymcp.toml (project id: {project_id})");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rexymcp_executor::config::Config;
    use tempfile::TempDir;

    #[test]
    fn init_writes_toml() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(dir.path().join("rexymcp.toml").exists());
    }

    #[test]
    fn init_writes_parseable_config() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        let path = dir.path().join("rexymcp.toml");
        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.provider, "openai");
        assert_eq!(cfg.executor.model, "qwen2.5-coder-32b");
        assert_eq!(cfg.executor.base_url, "http://localhost:1234/v1");
        assert_eq!(cfg.budget.context_length, 32768);
        assert_eq!(cfg.budget.max_context_pct, 70);
        assert_eq!(cfg.budget.max_turns, 200);
        assert_eq!(cfg.budget.escalation_slots, 1);
        assert_eq!(cfg.governor.identical_call_threshold, 6);
        assert_eq!(cfg.governor.verifier_persistence_threshold, 6);
        assert_eq!(cfg.governor.runaway_output_bytes, 102400);
        // project.id is a v4 UUID — 36 chars, format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        let pid = cfg.project.id.expect("project.id must be set by init");
        assert_eq!(pid.len(), 36, "project.id must be a UUID: {pid}");
        assert!(
            pid.chars().all(|c| c.is_ascii_hexdigit() || c == '-'),
            "project.id must contain only hex and dashes: {pid}"
        );
    }

    #[test]
    fn init_generates_unique_project_ids() {
        let dir1 = TempDir::new().unwrap();
        let dir2 = TempDir::new().unwrap();
        run(dir1.path(), false).unwrap();
        run(dir2.path(), false).unwrap();
        let id1 = Config::load(&dir1.path().join("rexymcp.toml"))
            .unwrap()
            .project
            .id
            .unwrap();
        let id2 = Config::load(&dir2.path().join("rexymcp.toml"))
            .unwrap()
            .project
            .id
            .unwrap();
        assert_ne!(id1, id2, "each init must produce a distinct project UUID");
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        let result = run(dir.path(), false);
        assert!(result.is_err());

        // File must still contain "OLD"
        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, "OLD");
    }

    #[test]
    fn init_force_overwrites() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        run(dir.path(), true).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert_ne!(content, "OLD");
        assert!(content.starts_with("# rexymcp.toml"));
    }

    #[test]
    fn init_does_not_write_mcp_json() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(!dir.path().join(".mcp.json").exists());
    }

    #[test]
    fn init_documents_models_override_section() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();

        let path = dir.path().join("rexymcp.toml");
        let content = fs::read_to_string(&path).unwrap();
        assert!(
            content.contains("[models.\""),
            "generated config must document the [models] override section"
        );

        // The [models] block is fully commented, so loading must succeed with an
        // empty models map.
        let cfg = Config::load(&path).expect("generated config must load");
        assert!(
            cfg.models.is_empty(),
            "commented [models] block must not populate config.models"
        );
    }
}
