use std::fs;
use std::io::Write;
use std::path::Path;

use uuid::Uuid;

fn generate_config(project_id: &str) -> String {
    format!(
        r#"# rexymcp.toml — executor configuration for this project.
# Generated by `rexymcp init`. Adjust values to match your setup.
# Reference: https://github.com/anthropics/rexyMCP

[project]
id = "{project_id}"              # stable UUID — identifies this project in telemetry

[executor]
provider = "openai"               # openai | ollama | lmstudio (all OpenAI-compatible)
model = "qwen2.5-coder-32b"       # model id as the endpoint knows it
base_url = "http://localhost:1234/v1"
# api_key = ""                    # optional; most local endpoints ignore it
# temperature = 0.2               # sampling temperature (omit for endpoint default)
# max_tokens = 8192               # per-response output token ceiling (default 8192)
# enable_thinking = false          # render the model's <think> reasoning block (default false = off)
# reasoning_effort = "medium"     # low | medium | xhigh, sent only when enable_thinking = true
# first_token_timeout_secs = 600  # wait before first token in seconds (default 600)
# stream_idle_timeout_secs = 240  # gap between tokens before timeout (default 240)
# task_tracking = true            # seed + track a per-session task list from the phase Spec (M12)

[budget]
context_length = 32768            # model context window in tokens
max_context_pct = 70              # trigger compaction above this % (0–100)
max_turns = 200                   # hard cap on executor turns per phase
wall_clock_secs = 0               # optional wall-clock ceiling in seconds (0 disables)

# [escalation]
# max_assists = 3                 # autonomous architect assists per phase (/rexymcp:auto loop)

[governor]
identical_call_threshold = 6      # consecutive identical tool calls → hard-fail
verifier_persistence_threshold = 6 # consecutive turns with verifier errors → hard-fail
runaway_output_bytes = 102400     # single tool output bytes → hard-fail (100 KB)
empty_completion_threshold = 3    # consecutive empty completions → hard-fail
gate_feedback_repeat_threshold = 5 # consecutive byte-identical gate-feedback re-injections → hard-fail
oscillation_window = 8            # sliding window scanned for A,B,A,B oscillation (0 disables)
oscillation_distinct_max = 2      # ≤ this many distinct calls in the window → hard-fail
output_window = 6                 # sliding window of tool outputs summed for flood check (0 disables)
output_window_bytes = 262144      # total bytes across the output window → hard-fail (256 KB)
read_only_stall_threshold = 60    # consecutive non-mutating tool calls → hard-fail; resets on any patch/write_file (0 disables)
novelty_window = 24               # trailing read-only calls examined for target novelty (0 disables)
novelty_distinct_floor = 6        # ≤ this many distinct normalized targets in the window → churn
novelty_action = "advisory"       # "advisory" (default): log low-novelty churn but keep running; "terminate": hard-fail on it

# [models."<model-id>"]              # per-model knob overrides; key is the exact
#                                    # active model id (no prefix/substring match).
#                                    # Any key omitted here inherits the global value above.
# task_tracking = false              # override [executor] task_tracking for this model
# temperature = 0.2                  # override [executor] temperature
# seed = 7                           # override [executor] seed
# max_tokens = 8192                  # override [executor] max_tokens
# enable_thinking = false            # override [executor] enable_thinking
# reasoning_effort = "low"          # override [executor] reasoning_effort
# identical_call_threshold = 8       # override [governor] identical_call_threshold
# verifier_persistence_threshold = 8 # override [governor] verifier_persistence_threshold
# runaway_output_bytes = 204800      # override [governor] runaway_output_bytes
# empty_completion_threshold = 3     # override [governor] empty_completion_threshold
# gate_feedback_repeat_threshold = 5 # override [governor] gate_feedback_repeat_threshold
# oscillation_window = 10            # override [governor] oscillation_window
# oscillation_distinct_max = 2       # override [governor] oscillation_distinct_max
# output_window = 8                  # override [governor] output_window
# output_window_bytes = 524288       # override [governor] output_window_bytes
# read_only_stall_threshold = 30     # override [governor] read_only_stall_threshold
# novelty_window = 24                # override [governor] novelty_window
# novelty_distinct_floor = 6         # override [governor] novelty_distinct_floor
# novelty_action = "terminate"       # override [governor] novelty_action

[commands]
# format = "cargo fmt --all"
# build = "cargo build"
# lint = "cargo clippy --all-targets --all-features -- -D warnings"
# test = "cargo test"
# lint_fix = "cargo clippy --fix --allow-dirty"
# format_fix = "cargo fmt --all"    # writing form; run by the post-write hook

[context]
output_filter = true              # filter/truncate bash output to conserve context

[architect]
# dispatch_model = "claude-sonnet-5"   # /rexymcp:auto delegates dispatch to this model (default: inherit)
# review_model = "claude-sonnet-5"     # /rexymcp:auto delegates review to this model (default: inherit)

[telemetry]
# dir = "/path/to/shared/telemetry"  # cross-project PhaseRun telemetry store
"#
    )
}

pub fn run(dir: &Path, force: bool) -> anyhow::Result<()> {
    if !dir.is_dir() {
        return Err(anyhow::anyhow!("not a directory: {}", dir.display()));
    }

    let path = dir.join("rexymcp.toml");

    if path.exists() && !force {
        eprintln!("rexymcp.toml already exists — use --force to overwrite");
        return Err(anyhow::anyhow!("rexymcp.toml already exists"));
    }

    let project_id = Uuid::new_v4().to_string();
    let config = generate_config(&project_id);

    let mut file = fs::File::create(&path)?;
    file.write_all(config.as_bytes())?;

    println!("wrote rexymcp.toml (project id: {project_id})");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rexymcp_executor::config::{Config, GovernorConfig, ModelOverride};
    use tempfile::TempDir;

    #[test]
    fn init_writes_toml() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(dir.path().join("rexymcp.toml").exists());
    }

    #[test]
    fn init_writes_parseable_config() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        let path = dir.path().join("rexymcp.toml");
        let cfg = Config::load(&path).unwrap();
        assert_eq!(cfg.executor.provider, "openai");
        assert_eq!(cfg.executor.model, "qwen2.5-coder-32b");
        assert_eq!(cfg.executor.base_url, "http://localhost:1234/v1");
        assert_eq!(cfg.budget.context_length, 32768);
        assert_eq!(cfg.budget.max_context_pct, 70);
        assert_eq!(cfg.budget.max_turns, 200);
        assert_eq!(cfg.escalation.max_assists, 3);
        // Every templated governor value is the code default — a drifted literal
        // in the template would otherwise silently misdocument the knob.
        assert_eq!(
            serde_json::to_value(cfg.governor).unwrap(),
            serde_json::to_value(GovernorConfig::default()).unwrap()
        );
        // project.id is a v4 UUID — 36 chars, format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        let pid = cfg.project.id.expect("project.id must be set by init");
        assert_eq!(pid.len(), 36, "project.id must be a UUID: {pid}");
        assert!(
            pid.chars().all(|c| c.is_ascii_hexdigit() || c == '-'),
            "project.id must contain only hex and dashes: {pid}"
        );
    }

    /// Field names of a `#[derive(Serialize)]` struct, as they appear as TOML keys.
    fn field_names<T: serde::Serialize>(value: &T) -> Vec<String> {
        serde_json::to_value(value)
            .expect("struct serializes to a JSON object")
            .as_object()
            .expect("struct serializes to a JSON object")
            .keys()
            .cloned()
            .collect()
    }

    #[test]
    fn template_spells_out_every_governor_knob() {
        // A parse-level assertion cannot catch an omission here: a missing key
        // silently inherits the serde default. Pin the template text against the
        // struct's own field list, so a new knob fails this test until templated.
        let toml = generate_config("test-id");
        for key in field_names(&GovernorConfig::default()) {
            assert!(
                toml.contains(&format!("\n{key} = ")),
                "[governor] block must spell out {key}: {toml}"
            );
        }
    }

    #[test]
    fn init_template_has_no_rate_keys() {
        // Delete-task 3/4 guard: the template must not resurrect `$/MTok`.
        let toml = generate_config("test-id");
        assert!(
            !toml.contains("per_mtok"),
            "template must not contain any per_mtok keys:\n{toml}"
        );
    }

    #[test]
    fn template_offers_every_per_model_override() {
        let toml = generate_config("test-id");
        for key in field_names(&ModelOverride::default()) {
            assert!(
                toml.contains(&format!("# {key} = ")),
                "[models] block must offer the {key} override: {toml}"
            );
        }
    }

    #[test]
    fn init_generates_unique_project_ids() {
        let dir1 = TempDir::new().unwrap();
        let dir2 = TempDir::new().unwrap();
        run(dir1.path(), false).unwrap();
        run(dir2.path(), false).unwrap();
        let id1 = Config::load(&dir1.path().join("rexymcp.toml"))
            .unwrap()
            .project
            .id
            .unwrap();
        let id2 = Config::load(&dir2.path().join("rexymcp.toml"))
            .unwrap()
            .project
            .id
            .unwrap();
        assert_ne!(id1, id2, "each init must produce a distinct project UUID");
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        let result = run(dir.path(), false);
        assert!(result.is_err());

        // File must still contain "OLD"
        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, "OLD");
    }

    #[test]
    fn init_force_overwrites() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("rexymcp.toml");
        fs::write(&path, "OLD").unwrap();

        run(dir.path(), true).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert_ne!(content, "OLD");
        assert!(content.starts_with("# rexymcp.toml"));
    }

    #[test]
    fn init_does_not_write_mcp_json() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();
        assert!(!dir.path().join(".mcp.json").exists());
    }

    #[test]
    fn init_documents_models_override_section() {
        let dir = TempDir::new().unwrap();
        run(dir.path(), false).unwrap();

        let path = dir.path().join("rexymcp.toml");
        let content = fs::read_to_string(&path).unwrap();
        assert!(
            content.contains("[models.\""),
            "generated config must document the [models] override section"
        );

        // The [models] block is fully commented, so loading must succeed with an
        // empty models map.
        let cfg = Config::load(&path).expect("generated config must load");
        assert!(
            cfg.models.is_empty(),
            "commented [models] block must not populate config.models"
        );

        // Verify enable_thinking appears in both [executor] and [models] blocks.
        assert!(
            content.contains("enable_thinking"),
            "generated config must document enable_thinking"
        );
        // Count occurrences — should appear in both [executor] and [models] blocks.
        let count = content.matches("enable_thinking").count();
        assert!(
            count >= 2,
            "enable_thinking should appear in both [executor] and [models] blocks, found {count}"
        );
    }
}
